name: Build AMI

on:
  release:
    types: [published]

env:
  AWS_REGION: eu-north-1

jobs:
  main:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set build variables
        run: |
          echo "PKR_VAR_aws_region=$AWS_REGION" >> $GITHUB_ENV
          echo "PKR_VAR_version=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Packer init
        run: packer init .

      - name: Packer validate
        run: packer validate .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Packer build
        run: packer build template.pkr.hcl
